# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
